glb.discountLevelData =[
   {
      "id" : 0,
      "Category" : 1,
      "item" : "0-15%",
      "numEvents" : 16,
      "sales" : 56.5,
      "volume" : 23,
      "margin" : 15,
      "profit" : 15,
      "transactions" : 12,
      "impact" : 1014.5,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 1,
      "Category" : 1,
      "item" : "15-30%",
      "numEvents" : 31,
      "sales" : 162,
      "volume" : 81,
      "margin" : 41,
      "profit" : 41,
      "transactions" : 45,
      "impact" : 1766,
      "isBest" : "true",
      "followUp" : "15-30% discount level has much higher margin performance than steeper discount levels",
      "action" : null,
      "hiddenAction" : "Identify item-tactic combinations driving high performance. Increase frequency of these event. Test similar tactics on other items in this category",
      "actionColor" : "yellow"
    },
    {
      "id" : 2,
      "Category" : 1,
      "item" : "30-45%",
      "numEvents" : 18,
      "sales" : 95,
      "volume" : 38.5,
      "margin" : 18,
      "profit" : 18,
      "transactions" : 36.5,
      "impact" : 1604,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 3,
      "Category" : 1,
      "item" : "45-60%",
      "numEvents" : 11,
      "sales" : 199,
      "volume" : 79,
      "margin" : -2,
      "profit" : 1,
      "transactions" : 49,
      "impact" : 2126,
      "isBest" : "false",
      "followUp" : null,
      "action" : "High discount level tactics consists 100% of BOGO tactics which are most margin dilutive",
      "hiddenAction" : "Reduce discount depth for this category and shift to lower discount level buckets.",
      "actionColor" : "red"
    },
    {
      "id" : 4,
      "Category" : 1,
      "item" : "60%+",
      "numEvents" : 0,
      "sales" : 0,
      "volume" : 0,
      "margin" : 0,
      "profit" : 0,
      "transactions" : 0,
      "impact" : 0,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 5,
      "Category" : 8,
      "item" : "0-15%",
      "numEvents" : 31,
      "sales" : 61,
      "volume" : 20,
      "margin" : 5,
      "profit" : 5,
      "transactions" : 39,
      "impact" : 1325,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 6,
      "Category" : 8,
      "item" : "15-30%",
      "numEvents" : 65,
      "sales" : 48,
      "volume" : 21,
      "margin" : 7,
      "profit" : 18,
      "transactions" : 19,
      "impact" : 1019,
      "isBest" : "true",
      "followUp" : null,
      "action" : "QTY discounts at various discount level between 0% and 25% on average create good lift and profit.",
      "hiddenAction" : "Discounts steeper than 25% drive are often margin dilutive.",
      "actionColor" : "green"
    },
    {
      "id" : 7,
      "Category" : 8,
      "item" : "30-45%",
      "numEvents" : 66,
      "sales" : 108,
      "volume" : 57,
      "margin" : -3,
      "profit" : 5,
      "transactions" : 49,
      "impact" : 1892,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 8,
      "Category" : 8,
      "item" : "45-60%",
      "numEvents" : 91,
      "sales" : 242,
      "volume" : 81,
      "margin" : -132,
      "profit" : -65,
      "transactions" : 103,
      "impact" : 2213,
      "isBest" : "false",
      "followUp" : null,
      "action" : "Reduce portion of promos going steeper than 45% in discount level as they drive a significant portion of category margin loss",
      "hiddenAction" : "Reduce BOGOS. Reduce steeply discounted QTY offers",
      "actionColor" : "red"
    },
    {
      "id" : 9,
      "Category" : 8,
      "item" : "60%+",
      "numEvents" : 0,
      "sales" : 0,
      "volume" : 0,
      "margin" : 0,
      "profit" : 0,
      "transactions" : 0,
      "impact" : 0,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 10,
      "Category" : 5,
      "item" : "0-15%",
      "numEvents" : 63,
      "sales" : 5.5,
      "volume" : 2,
      "margin" : 2,
      "profit" : 2,
      "transactions" : 2,
      "impact" : 497,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 11,
      "Category" : 5,
      "item" : "15-30%",
      "numEvents" : 125,
      "sales" : 23.25,
      "volume" : 11.5,
      "margin" : 1.5,
      "profit" : 5.75,
      "transactions" : 7.5,
      "impact" : 1000,
      "isBest" : "true",
      "followUp" : null,
      "action" : "Continue promotions within 15-30% discount range",
      "hiddenAction" : null,
      "actionColor" : "yellow"
    },
    {
      "id" : 12,
      "Category" : 5,
      "item" : "30-45%",
      "numEvents" : 38,
      "sales" : 33.5,
      "volume" : 16,
      "margin" : -7.5,
      "profit" : -2,
      "transactions" : 13,
      "impact" : 1271,
      "isBest" : "false",
      "followUp" : "QTY discounts from 30-45% vary in effectiveness",
      "action" : null,
      "hiddenAction" : "Identify which specific tactics driving margin dilution and reduce discount depth",
      "actionColor" : "yellow"
    },
    {
      "id" : 13,
      "Category" : 5,
      "item" : "45-60%",
      "numEvents" : 247,
      "sales" : 43,
      "volume" : 21,
      "margin" : -38.5,
      "profit" : -13.5,
      "transactions" : 17,
      "impact" : 2597,
      "isBest" : "false",
      "followUp" : null,
      "action" : null,
      "hiddenAction" : null,
      "actionColor" : null
    },
    {
      "id" : 14,
      "Category" : 5,
      "item" : "60%+",
      "numEvents" : 0,
      "sales" : 0,
      "volume" : 0,
      "margin" : 0,
      "profit" : 0,
      "transactions" : 0,
      "impact" : 0,
      "isBest" : "false",
      "followUp" : null,
      "action" : "Over 50% of discounts in this category fall in the 45-60% discount range and drive over 75% margin loss",
      "hiddenAction" : null,
      "actionColor" : "red"
    }
]